package com.telefonica.movistar.planfs.constant;

public class Examples {

	public Examples() {
		throw new UnsupportedOperationException("Utility class");
	}

	public static final String REQUEST_EXAMPLE = "{\n"
			+ "    \"peticion\": {\n"
			+ "        \"idContacto\": \"idContacto\",\n"
			+ "        \"descIncEureka\": \"fCBQcnVlYmFzIHx8IEFQUCB8IGlkZW50aWZpY2FkbyBjb24gfCBDQyB8fCAxOTE1MDc3OCB8IHkgdXN1YXJpbyB8IHBydWViYXNhcHB2MUBnbWFpbC5jb20gfCBpbmljaW8gc2VzafNuIGNvbiBsYSBs7W5lYSB8IDMxODY0OTcxNzEgfCBkZXNkZSBNaSBNb3Zpc3RhciBhIHRyYXbpcyBkZSBsYSBhcGxpY2FjafNuIEFQUE1PVklMIGVsIHwgMTAvMDQvMjAxNyB8fCAxODoxMzoxOSB8Lg\"\n"
			+ "    }\n"
			+ "}";
	

	public static final String R2_SUCCESSFUL_RESPONSE = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:head=\"http://telefonica.com/globalIntegration/header\" xmlns:v1=\"http://telefonica.com/globalIntegration/services/QueryPurchasedOffering/v1\">\n"
			+ "   <soapenv:Header>\n"
			+ "      <head:HeaderOut>\n"
			+ "         <head:originator>?</head:originator>\n"
			+ "         <head:destination>?</head:destination>\n"
			+ "         <!--Optional:-->\n"
			+ "         <head:pid>?</head:pid>\n"
			+ "         <head:execId>?</head:execId>\n"
			+ "         <!--Optional:-->\n"
			+ "         <head:msgId>?</head:msgId>\n"
			+ "         <head:timestamp>?</head:timestamp>\n"
			+ "         <!--Optional:-->\n"
			+ "         <head:msgType>?</head:msgType>\n"
			+ "         <!--Optional:-->\n"
			+ "         <head:varArg>\n"
			+ "            <!--1 to 10 repetitions:-->\n"
			+ "            <head:arg>\n"
			+ "               <head:key>?</head:key>\n"
			+ "               <head:values>\n"
			+ "                  <!--1 to 10 repetitions:-->\n"
			+ "                  <head:value>?</head:value>\n"
			+ "               </head:values>\n"
			+ "            </head:arg>\n"
			+ "         </head:varArg>\n"
			+ "      </head:HeaderOut>\n"
			+ "   </soapenv:Header>\n"
			+ "   <soapenv:Body>\n"
			+ "      <v1:queryPurchasedOfferingResponse>\n"
			+ "         <v1:rspBodyQPOItem>\n"
			+ "            <!--Zero or more repetitions:-->\n"
			+ "            <v1:offeringInstanceQPOItem>\n"
			+ "               <v1:idBundledProductOffering>?</v1:idBundledProductOffering>\n"
			+ "               <v1:idParameter>?</v1:idParameter>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:nameProductOffering>?</v1:nameProductOffering>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:shortNameProductOffering>?</v1:shortNameProductOffering>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:offeringDescriptionInfo>?</v1:offeringDescriptionInfo>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:brandInfo>?</v1:brandInfo>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:categoryProductOffering>?</v1:categoryProductOffering>\n"
			+ "               <v1:secondReqFlag>?</v1:secondReqFlag>\n"
			+ "               <v1:secondReqAuxFlag>?</v1:secondReqAuxFlag>\n"
			+ "               <v1:interactionStatusBusinessInteraction>?</v1:interactionStatusBusinessInteraction>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:statusDetailInfo>?</v1:statusDetailInfo>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:customerStatusTime>?</v1:customerStatusTime>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:relaPrimaryOfferingInstanceIdInfo>?</v1:relaPrimaryOfferingInstanceIdInfo>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:parentIdInfo>?</v1:parentIdInfo>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:startDateTimeTimePeriod>?</v1:startDateTimeTimePeriod>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:endDateTimeTimePeriod>?</v1:endDateTimeTimePeriod>\n"
			+ "               <!--Optional:-->\n"
			+ "               <v1:salesInformationQPOItem>\n"
			+ "                  <!--Optional:-->\n"
			+ "                  <v1:SalesManagerID>?</v1:SalesManagerID>\n"
			+ "                  <!--Optional:-->\n"
			+ "                  <v1:channelTypeInfo>?</v1:channelTypeInfo>\n"
			+ "               </v1:salesInformationQPOItem>\n"
			+ "               <!--Zero or more repetitions:-->\n"
			+ "               <v1:propertyQPOItem>\n"
			+ "                  <v1:idParameter>?</v1:idParameter>\n"
			+ "                  <!--Optional:-->\n"
			+ "                  <v1:valueParameter>?</v1:valueParameter>\n"
			+ "               </v1:propertyQPOItem>\n"
			+ "            </v1:offeringInstanceQPOItem>\n"
			+ "         </v1:rspBodyQPOItem>\n"
			+ "      </v1:queryPurchasedOfferingResponse>\n"
			+ "   </soapenv:Body>\n"
			+ "</soapenv:Envelope>";


}
